POST http://localhost:5135/api/requests
Content-Type: application/json

{
  "requestDescription": "Тестовая заявка №11",
  "brigadeId": 2
}
###
GET http://localhost:5135/api/requests/18
###
GET http://localhost:5135/api/requests/
###
PUT http://localhost:5135/api/requests/4
Content-Type: application/json

{
  "requestDescription": "Тестовая заявка №4",
  "brigadeId": 3,
  "statusId": 3,
  "finishDate": "2025-04-30",
  "requestNote": "Все прошло штатно"
}

###
PUT http://localhost:5135/api/requests/close/6
Content-Type: application/json

{
    "requestNote": "Все прошло нештатно"
}
###
DELETE http://localhost:5135/api/requests/1
###
GET http://localhost:5135/api/reports/monthly?year=2025&month=6

